
version: '3'

services:
    webserver:
        image: yangzl/webserver:latest
        container_name: webserver
        restart: always
        volumes:
            - /Users/zhaoliuyang/Desktop/conf:/data
        environment:
            - TZ=Asia/Shanghai
        ports:
            - 80:80
        network_mode: bridge

        stdin_open: true    # -i interactive
        tty: true           # -t tty
